export const USER_LOGIN_REQUEST = 'LOGIN_USER_REQUEST';
export const USER_LOGIN_SUCCESS = 'LOGIN_USER_SUCCESS';
export const USER_LOGIN_FAIL = 'LOGIN_USER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
